local vim = vim
local Plug = vim.fn['plug#']

vim.call('plug#begin')

Plug('scrooloose/nerdtree')
Plug('Xuyuanp/nerdtree-git-plugin')
Plug('moll/vim-bbye')
Plug('neovim/nvim-lspconfig')
Plug('roxma/nvim-yarp')
Plug('ncm2/ncm2')
Plug('ncm2/ncm2-path')
Plug('ncm2/ncm2-bufword')
Plug('ncm2/ncm2-cssomni')
Plug('kburdett/vim-nuuid')
Plug('jiangmiao/auto-pairs')
Plug('tpope/vim-commentary')
Plug('tpope/vim-repeat')
Plug('dracula/vim', { ['as'] = 'dracula' })
Plug('sheerun/vim-polyglot')
Plug('farfanoide/vim-kivy')
Plug('romainl/vim-qf')
Plug('yssl/QFEnter')
Plug('mhinz/vim-grepper')
Plug('ctrlpvim/ctrlp.vim')
Plug('dense-analysis/ale')
Plug('bling/vim-airline')
Plug('tpope/vim-fugitive')
Plug('airblade/vim-gitgutter')
Plug('elzr/vim-json')
Plug('othree/jspc.vim')
Plug('tpope/vim-surround')
Plug('ryanoasis/vim-devicons')
Plug('nathanaelkane/vim-indent-guides')
Plug('ap/vim-css-color')

vim.call('plug#end')

vim.cmd('source legacy.vim')
